### PR TITLE
[cmsv2] Fix date picker

### LINKED ISSUE #1711: [cms-v2] Opening the datepicker when the exchange rate is being fetched locks the picker
bug_select_date

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Fixes #1711 

Replace useEffect hook with useLayoutEffect hook and remove the prop dependency list

### CODE REVIEW

File: src/componentsv2/MonthPicker/MonthPickerField.jsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ const pickerLang = {
   to: "To"
 };
 
-const makeText = m => {
+const makeText = (m) => {
   if (m && m.year && m.month)
     return pickerLang.months[m.month - 1] + " " + m.year;
```
Comment (amassarwi) [inline src/componentsv2/MonthPicker/MonthPickerField.jsx]: We could use here template string instead
