### PR TITLE
fix: use short token when displaying legacy proposal.

### LINKED ISSUE #2419: proposals-archive: Broken comment links.
See details below:

image

### PR DESCRIPTION
**Pull request by amassarwi**
With this diff all archive proposals seem to have the right URL for the comments section:
image

### CODE REVIEW

File: src/containers/Proposal/hooks/useProposalURLs.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export default function useProposalURLs(
   const { javascriptEnabled } = useConfig();
   // TODO: remove legacy
   const legacyProposals = useSelector(sel.legacyProposals);
-  const isLegacy = legacyProposals.includes(proposalToken);
+  const isLegacy = legacyProposals.includes(shortRecordToken(proposalToken));
```
Comment (amassarwi) [inline src/containers/Proposal/hooks/useProposalURLs.js:19]: `legacyPropsoals` list includes short tokens so we needed to compare against the short version of the token
when searching for the record token.

**Review by tiagoalvesdulce — APPROVED** [review]
