### PR TITLE
[redesign] Fix initial load flickering in account's proposals tab

### LINKED ISSUE #1464: [redesign] Proposals tab in account page flickering on initial load
This happens when a user doesn't have any proposals submitted under his account.

### PR DESCRIPTION
**Pull request by amassarwi**
- closes #1464

### CODE REVIEW

File: src/containers/Proposal/User/Submitted.jsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ const Proposals = props => {
           renderItem={renderProposal}
           onFetchMore={handleFetchMoreProposals}
           hasMore={hasMoreToLoad}
-          isLoading={loading}
+          isLoading={loading || !initialFetchDone}
```
Comment (amassarwi) [inline src/containers/Proposal/User/Submitted.jsx]: This fixed the flickering

File: src/containers/Proposal/User/hooks.js [hunk 2]
```diff
@@ -61,9 +61,9 @@ export function useUserProposals(ownProps) {
       numOfUserProposals: sel.numOfUserProposals,
       loading: or(
         sel.userProposalsIsRequesting,
-        sel.isApiRequestingPropsVoteStatus
+        sel.isApiRequestingProposalsVoteSummary
```
Comment (amassarwi) [inline src/containers/Proposal/User/hooks.js]: Related to #1374 - we trigger vote summary call and not vote status anymore to fetch vote related info

File: src/containers/Proposal/User/hooks.js [hunk 3]
```diff
@@ -61,9 +61,9 @@ export function useUserProposals(ownProps) {
...
       ),
-      error: or(sel.userProposalsError, sel.apiPropVoteStatusError)
+      error: or(sel.userProposalsError, sel.apiPropsVoteSummaryError)
```
Comment (amassarwi) [inline src/containers/Proposal/User/hooks.js]: Same as above
