### PR TITLE
fix: Autofocus adjustments on 2FA digits input.

### LINKED ISSUE #2550: 2fa default to first input box
When politeiagui opens the 2fa modal, you have to manually click the first input box in order to start entering your 2fa code.

image

A better UX would be to default to having the first input box already selected so that I can start entering the code without having to click anything.

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #2550 

This PR fixes an issue that requested improvements on Two-Factor Authentication digits input regarding its autofocus. Now, the input gets automatically focused after display if the `autoFocus` prop is `true`.

### UI Changes Screenshot
Haven't clicked anywhere after the 2FA modal shows up:
2550-2fa-focus

### CODE REVIEW

**Review by lukebp — CHANGES_REQUESTED** [review]
Found a minor bug.

If you change windows, such as if you pull up your desktop 2fa app to get the 2fa code, the autofocus gets cleared out.

**Comment by lukebp** [comment]
Are you able to add tests for this?

File: src/components/DigitsInput/DigitsInput.jsx [hunk 1]
```diff
@@ -36,17 +43,28 @@ const DigitsInput = ({ length, onChange, className, code, tabIndex }) => {
...
+  // on render because useEffect does not recognize changes
+  // for references, therefore, inputRef cannot be used as
+  // a dependency
+  useEffect(() => {
+    focused && inputRef.current.focus();
+  }, [focused]);
+
+  useEffect(() => {
+    setFocused(autoFocus);
+  }, [autoFocus]);
```
Comment (tiagoalvesdulce) [inline src/components/DigitsInput/DigitsInput.jsx:56]: Can we get rid of this if we use `const [focused, setFocused] = useState(autoFocus);` ?

**Review by tiagoalvesdulce — COMMENTED** [review]
Left an inline comment

File: src/components/DigitsInput/DigitsInput.jsx (hunk 1 above)
Comment (tiagoalvesdulce) [reply src/components/DigitsInput/DigitsInput.jsx:56]: Nice! Makes sense. Thanks.

**Review by lukebp — APPROVED** [review]
tACK

File: src/components/DigitsInput/DigitsInput.jsx [hunk 2]
```diff
@@ -36,12 +43,23 @@ const DigitsInput = ({ length, onChange, className, code, tabIndex }) => {
     inputRef.current.focus();
   };
 
+  // Both useEffects are used to trigger the input focus
+  // on render because useEffect does not recognize changes
+  // for references, therefore, inputRef cannot be used as
+  // a dependency
+  useEffect(() => {
```
[the remark this answers is not in the document]
Comment (tiagoalvesdulce) [reply src/components/DigitsInput/DigitsInput.jsx:50]: Just adding to this. It's often a good idea to split up `useEffects` if you can. Even better if you isolate them in custom hooks if they are big and/or reused through the code.

**Comment by lukebp** [comment]
Needs final approval from @tiagoalvesdulce.

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM. Remember to use https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md#44-model-git-commit-messages in the PR description in the future. It's easier for the reviewer to merge since the commit description can be reused.
