### PR TITLE
[cms] Fix invoice attachments

### LINKED ISSUE #1900: [cms] Attachments while attempting to edit not working
When attempting to attach while editing an existing invoice, it doesn't work.   You are able to select the file, but then you are brought back to the "Select File" modal and nothing appears on the invoice form.  

Even worse I had attached an image to the invoice previously, and then tried to attach another while editing.  After submiting the edit, all attachments were gone.

### PR DESCRIPTION
**Pull request by amassarwi**
### Bug & solution description
This diff fixes few issues regarding invoices attachments:
 - Map correct BE invoice record files property to initial values object
 - Define files custom files validation and call it on files change
 - Fire `global` error message when files aren't valid, and disable submit button.

#### Use Cases
1. Create invoice
2. Edit invoice

Fixes #1900

### CODE REVIEW

File: src/components/InvoiceForm/InvoiceForm.jsx [hunk 1]
```diff
@@ -30,19 +34,24 @@ const InvoiceForm = React.memo(function InvoiceForm({
...
-  }, [errors]);
+  const files = values.files;
+  useEffect(
+    function scrollToTopOnGlobalError() {
+      if (errors.global) {
+        window.scrollTo(0, 0);
+      }
+    },
+    [errors]
+  );
```
Comment (tiagoalvesdulce) [inline src/components/InvoiceForm/InvoiceForm.jsx:54]: I think this could be moved to a custom hook. What do you think?

File: src/components/InvoiceForm/InvoiceForm.jsx [hunk 2]
```diff
@@ -79,10 +92,12 @@ const InvoiceForm = React.memo(function InvoiceForm({
 
   const handleFileRemoval = useCallback(
     (v) => {
-      const fs = values.files.filter((f) => f.payload !== v.payload);
+      const fs = files.filter(
+        (f) => f.payload !== v.payload && f.name !== v.name
```
Comment (tiagoalvesdulce) [inline src/components/InvoiceForm/InvoiceForm.jsx:96]: hmm, why do we need to check the name and the payload here? Asking because only the payload should be enough...

File: src/components/InvoiceForm/InvoiceForm.jsx (hunk 1 above)
Comment (amassarwi) [reply src/components/InvoiceForm/InvoiceForm.jsx:54]: Yep, good idea

File: src/components/InvoiceForm/InvoiceForm.jsx (hunk 2 above)
Comment (amassarwi) [reply src/components/InvoiceForm/InvoiceForm.jsx:96]: You are right, I was uploading same image with different names and it was deleting both, I will revert it, should be stricter condition to filter out duplicates.
