### PR TITLE
Fixes invoice counts for date filter

### LINKED ISSUE #1090: Invoices tab counting must be updated accordingly to date filter
The invoices counting are not being updated when the invoice list is filtered by month & year.
See screenshot below:
Screen Shot 2019-04-15 at 12 30 18

### PR DESCRIPTION
**Pull request by thi4go**
closes #1090

### CODE REVIEW

File: src/selectors/app.js [hunk 1]
```diff
@@ -434,7 +442,7 @@ const getInvoicesByYear = (invoices, year) =>
 const getInvoicesByMonth = (invoices, month) =>
```
Comment (fernandoabolafio) [inline src/selectors/app.js]:
```suggestion
const getInvoicesByMonth = (invoices = [], month) =>
```

File: src/selectors/app.js [hunk 2]
```diff
@@ -434,7 +442,7 @@ const getInvoicesByYear = (invoices, year) =>
...
   month === FILTER_ALL_MONTHS
     ? invoices
-    : invoices.filter(i => i.input.month === month);
+    : invoices.filter(i => i.input.month === month + 1);
```
Comment (fernandoabolafio) [inline src/selectors/app.js]:
```suggestion
    : invoices.filter(i => i.input.month === month);
```

**Comment by thi4go** [comment]
Hey @fernandoabolafio thanks for the review, should work properly now. I put the +1 offset on the months because locally on my env I was getting the inverse behaviour, that is, months were being offset by one. When I chose April, for example, March invoices got listed. Maybe something in my data. But anyways, should be working properly now. 👍
