### PR TITLE
fix: Proposal diff bugs

### LINKED ISSUE #2583: Proposal diff bugs.
While navigating on proposals app, I noticed that diff is not working for censored proposals and unvetted proposals when user is not the author or admin. Also, noticed that the Diff modal is triggering duplicate requests and looks weird for mobile screens. See below:

1. Censored proposals diff bug:
    diff-censored-bug

2. Unvetted proposals for users that aren't admins or authors:
    diff-unvetted-bug

3. Duplicate details request on diff modal:
    diff-duplicate-requests

4. Edited timestamps being overlayed for mobile screens (using an iPhone X screen resolution):
    Screen Shot 2021-09-14 at 1 55 39 PM

### PR DESCRIPTION
**Pull request by vibros68**
closes #2583

This diff fixes some bugs on proposal diff version.
* Fix: after clicking on version button, duplicate request are sent to
the server.
* Fix: Hide the version button when the proposal is cencered or when
the proposal is unvetted and the user is not admin or author.
* Fix: Title text is overlap in the mobile screen.
Screenshot from 2021-10-20 21-03-47

### CODE REVIEW

File: src/components/ModalDiff/hooks.js [hunk 1]
```diff
@@ -1,46 +1,97 @@
...
+            if (setVersionsQueue.length) {
+              return send(START);
+            }
+            return send(RESOLVE);
+          })
+          .catch((e) => send(REJECT, e));
+
+        return send(FETCH);
+      },
+      done: () => {}
```
Comment (victorgcramos) [inline src/components/ModalDiff/hooks.js:87]: AWESOME! Good job here, mate!
