### PR TITLE
fix external link handler and url preview

### LINKED ISSUE #1047: External link warning modal issues
1.
One of the issues highlighted in https://github.com/decred/politeiagui/issues/960 is back. The modal should close if the back button is pressed. 

2.

I also found that if the URL of the website contains a hash "#" (fragment identifier) then anything after that is not shown in the warning. This needs to be fixed since in many websites the content is dynamically loaded based on the fragment identifier. 

image

### PR DESCRIPTION
**Pull request by camus-code**
Closes #1047 

Fixes onClose behavior when path changes for modals. Also updates URL preview in external link modal to show entire url, including query strings and fragment identifiers

### CODE REVIEW

File: src/components/Modal/ModalStack.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ class ModalStack extends React.Component {
     const welcomeModal = openedModals.filter(
```
Comment (fernandoabolafio) [inline src/components/Modal/ModalStack.js]: I think it could be better written like this:

```js
const welcomeModaIOpened = openModals.find(modal => moda.type === WELCOME_MODAL)
```

See next comment

File: src/components/Modal/ModalStack.js [hunk 2]
```diff
@@ -34,7 +35,7 @@ class ModalStack extends React.Component {
         else document.querySelector("body").style.overflowY = "scroll";
       });
     // closes modals if user path has changed except when it's the user's first access
-    if (location.pathname !== prevProps.location.pathname && !welcomeModal) {
+    if (location.pathname !== prevProps.location.pathname && noWelcomeModal) {
```
Comment (fernandoabolafio) [inline src/components/Modal/ModalStack.js]:
```suggestion
    if (location.pathname !== prevProps.location.pathname && !welcomeModalOpened) {
```

File: src/components/Modal/ModalStack.js [hunk 3]
```diff
@@ -16,6 +16,7 @@ class ModalStack extends React.Component {
     const welcomeModal = openedModals.filter(
       modal => modal.type === WELCOME_MODAL
     );
+    const noWelcomeModal = welcomeModal.length === 0;
```
Comment (fernandoabolafio) [inline src/components/Modal/ModalStack.js]:
```suggestion
```

File: src/components/Modal/ModalStack.js (hunk 1 above)
Comment (camus-code) [reply src/components/Modal/ModalStack.js]: Good suggestion to use .find that's a lot cleaner than filter. PR is up
