### PR TITLE
[cms] Fix Supervisor ID's list

### LINKED ISSUE #1937: [cms] Unable to set supervisor for subcontractor
Currently it shows a dropdown but shows "no options" and i'm unable to manually fill in anything there.

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff closes #1937 issue, which reported a bug with the supervisor ids selector on Manage Contractor form. No options were being shown.

### Solution description

The list of supervisors options was empty because it was getting information from user's supervisor list, not the supervisors list available on the CMS platform. The solution is: create a `useSupervisors` hook to fetch all supervisors (since this can only be performed by admins) and populate the selector's options to display them.

#### Use Cases (if needed)

The `useSupervisors` hook can be used for fetching supervisors.

### UI Changes Screenshot

Before:
Captura de Tela 2020-05-26 às 00 21 02

After:
Captura de Tela 2020-05-26 às 00 20 26

### CODE REVIEW

File: src/containers/User/Detail/ManageContractor/ManageDccForm.jsx [hunk 1]
```diff
@@ -1,47 +1,54 @@
...
-        };
-      }),
-    [users]
+      supervisorsOptions.filter((option) =>
+        supervisoruserids.some((supervisorid) => supervisorid === option.value)
+      ),
+    [supervisorsOptions, supervisoruserids]
   );
 
+  const isLoading =
```
Comment (tiagoalvesdulce) [inline src/containers/User/Detail/ManageContractor/ManageDccForm.jsx:49]: Do we really have to check for undefined? what are the possible types of `domain` and `contractortype`? Maybe we can improve this logical expression

Comment (victorgcramos) [reply src/containers/User/Detail/ManageContractor/ManageDccForm.jsx:49]: hey! This checking is done because domains and contractortypes can both be `0`. This is why we check if they are `undefined`
