### PR TITLE
fix: tweaks on invoice datasheet and user detail

### LINKED ISSUE #2154: [cms] Opening link loads blank page
I am not currently logged in, and I clicked on this link shared by @degeri on Matrix: https://cms.decred.org/user/UUID?tab=proposals%20owned

I am taken to a blank page which shows only the CMS logo in the top left corner and a Dark Mode toggle in the top right.

I would expect a redirect to the login page if this is a valid URL, or a 404 if not valid.

### LINKED ISSUE #2155: [cms] Filter out RFP proposals from invoice dropdowns
We shouldn't allow the selection of RFP proposals in the dropdown (since they aren't proposals to be billed against).  

This should be possible by looking at whether LinkBy is > 0 in the ProposalMetadata returned in the ProposalRecords from the BatchProposals call.

### LINKED ISSUE #2159: [cms] Render Type column as text
I'm having Type column cells shown as `1` instead of `Labor`. Not sure if there's an issue with my browser but other columns look correct. Specifically, Domain and Proposal columns that also use drop downs are shown correctly.

### LINKED ISSUE #2173: [cms] Edit DCC Info button should not be visible for non-admins
I open my user account page (`/user/uuid..`) and on the Manage Contractor tab there is DCC Info section and an `Edit` button. If I click it, loading indicator spins for a few seconds and the button just disappears. I think it should not be visible in the first place if I am not an admin.

### LINKED ISSUE #2174: [cms] Drafts tab is shown in other user accounts
I see Drafts tab not only in my Account but in any other, and it shows my drafts.

### LINKED ISSUE #2199: [cms] Megabytes of data fetched on Account views
On Account > Manage Contractor tab I see 3 requests to `/api/v1/proposals/batch` fetching a total of 3.2 _megabytes_ of data (2.3 MB compressed). I guess it is the entire proposals database.

Same happens on Owned Proposals tab.

As a user, all I see that is needed on these views are IDs and titles of my owned proposals.

I'm not sure if it's solely a frontend or backend issue, or both, hence submitting to politeiagui.

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff is a batch of minor fixes:

- redirects not logged in users to home page on CMS when accessing user details page (#2154).
- remove RFP proposals from invoice form (#2155)
- show type as text on invoice lineitems (#2159)
- show draft tab only for owners (#2174)

Closes #2154 
Closes #2155 
Closes #2159 
Closes #2173
Closes #2174 
Closes #2199

### CODE REVIEW

File: src/actions/api.js [hunk 1]
```diff
@@ -456,15 +456,18 @@ export const onFetchUser = (userId) => (dispatch) => {
...
     .then((response) =>
       dispatch(
         act.RECEIVE_USER({
           user: {
             ...response.user,
-            userid: userId
+            userid: userId,
+            // cmsinfo is used to identify whether
+            // user details request is for cms or pi
+            cmsinfo: isCMS
```
Comment (thi4go) [inline src/actions/api.js:470]: cmsinfo seems like it will contain several user informations, and not just a boolean indicating if it is from cms or not. I suggest changing this to isCMS, or something more with a boolean feel :+1:

File: src/hooks/api/useApprovedProposals.js [hunk 2]
```diff
@@ -1,32 +1,42 @@
...
-  const isLoading = isEmpty(proposals) || !proposalsTokens.approved;
+  const nonRfpProposals = useMemo(
+    () => proposals && Object.values(proposals).filter((p) => !p.linkby),
+    [proposals]
+  );
 
   return {
     proposals: Object.values(proposals),
     proposalsByToken: proposals,
+    nonRfpProposals,
```
Comment (thi4go) [inline src/hooks/api/useApprovedProposals.js:39]: what do you think of `proposalsNonRFP`? for more consistency with the other values we return on this hook

**Review by thi4go — APPROVED** [review]
Hey mate thanks for this PR, nice job. Tested and all mentioned issues were fixed. LGTM

Left minor naming suggestions :+1:

**Review by alexlyp — APPROVED** [review]

**Review by tiagoalvesdulce — APPROVED** [review]
