### PR TITLE
[cms] Fix invoice lineitems selector

### LINKED ISSUE #1866: [cms] Lineitem's dropdown fields are broken
Currently when clicking on of the dopdown items the value doesn't change!

### PR DESCRIPTION
**Pull request by victorgcramos**
Fixes #1866

### CODE REVIEW

File: src/components/InvoiceDatasheet/components/SelectEditor.jsx [hunk 1]
```diff
@@ -12,15 +13,23 @@ const customStyles = {
   })
 };
 
-const SelectEditor = ({ value, options, onCommit }) => {
-  const handleChange = ({ value }) => {
+const SelectEditor = ({ value, options, onChange, onCommit }) => {
+  const [newValue, setNewValue] = useAsyncState({ value });
```
Comment (amassarwi) [inline src/components/InvoiceDatasheet/components/SelectEditor.jsx:17]: Maybe we could use `getValueObj` to get initial value object ?
```suggestion
  const [newValue, setNewValue] = useAsyncState(getValueObj(value));
```
