### PR TITLE
Display the correct public key on account page and set message while …

### LINKED ISSUE #342: Wrong public key displayed on account page
- Go to /user/account
- Refresh the page
The public key being displayed isn't correct, now:
- Click on the username and account. 
The page will be updated and the correctly public key will be displayed:

wrong-pk

### PR DESCRIPTION
**Pull request by fernandoabolafio**
…loading it from storage
closes #342

### CODE REVIEW

File: src/components/AccountPage.js [hunk 1]
```diff
@@ -22,17 +23,26 @@ class KeyPage extends React.Component {
...
-    myPubKeyHex(loggedInAsEmail).then(pubkey => {
-      if(!this.unmounting) {
-        this.setState({ pubkey });
-      }
-    });
+    this.resolvePubkey();
+  }
+
+  componentDidUpdate() {
+    this.resolvePubkey();
```
Comment (sndurkin) [inline src/components/AccountPage.js]: Should we re-resolve the public key on every update?

Comment (fernandoabolafio) [reply src/components/AccountPage.js]: The function is being called but the code inside only executes if the condition `!this.state.pubkey && this.props.loggedInAsEmail` is fulfilled. I can move the condition out of the `resolvePubKey` if you think it can get more readable.

Comment (fernandoabolafio) [reply src/components/AccountPage.js]: Btw, I couldn't figure it out with another lifecycle since it is a mix of state change and prop changes.

Comment (sndurkin) [reply src/components/AccountPage.js]: That's a good point that the condition is already inside the function, I missed that.
