### PR TITLE
Malformed links redirecting to proposals/:id page

### LINKED ISSUE #633: Malformed links redirecting to proposals/:id page
Links without `http://` or `https://` are being treated as a politeiagui route.

Go to https://test-proposals.decred.org/proposals/0873814acca0322986c94dd7408c54dbab17815bbed64b938780514a811ee2f9 and click the first comment to reproduce.

### PR DESCRIPTION
**Pull request by victorgcramos**
Fixes #633

### CODE REVIEW

File: src/components/snew/Markdown/helpers.js [hunk 1]
```diff
@@ -2,6 +2,16 @@ import React from "react";
 import xssFilters from "xss-filters";
 import * as modalTypes from "../../Modal/modalTypes";
 
+function extractHostname(url) {
```
Comment (dajohi) [inline src/components/snew/Markdown/helpers.js]: Can this be simplified to https://nodejs.org/api/url.html#url_url_hostname?

**Comment by tiagoalvesdulce** [comment]
`new URL()` doesn't work properly if the provided URL is not prefixed with `http` or `https`, which is the exact use case @victorgcramos is handling. So, his function looks good.
