### PR TITLE
Disable 'comments' tab

### LINKED ISSUE #1100: Comments tab on Account page not working
The tab is there but when clicked gives a message: "This feature has not been implemented yet." If the feature will not be implemented for some time it may be better to hide the tab.

### PR DESCRIPTION
**Pull request by victorgcramos**
Fixes #1100

### CODE REVIEW

File: src/components/UserDetail/Page.js [hunk 1]
```diff
@@ -29,6 +27,7 @@ const UserDetailPage = ({
   numOfUserProposals,
   isCMS
 }) => {
+  console.log(tabId);
```
Comment (fernandoabolafio) [inline src/components/UserDetail/Page.js]: Please, remove this log
