### PR TITLE
fix: 2FA modal screen flickering.

### LINKED ISSUE #2556: 2FA error flow
If you input the wrong 2FA code the 2FA modal is closed out and the error message is displayed on the login screen.  The use must click the login button to re-attempt the 2FA code.  A better UX, and one that @victorgcramos has already implemented on the login modal in #2548, is to display the error message on the 2FA modal instead of the login screen so that the user does not have to click the login button again when re-inputing the 2FA code.

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #2556 

This diff fixes the screen flickering for failing 2FA modal actions
on Firefox by using a modal wrapper for the 2FA modal to prevent it
from re-renders.

### UI Changes

**Before:**
2556-2fa-modal-flicker-before

**After:**
2556-2fa-modal-flicker

### CODE REVIEW

**Review by lukebp — APPROVED** [review]
tACK

Tested on firefox.  Looks good.

**Comment by lukebp** [comment]
Needs approval from @tiagoalvesdulce.

File: src/components/ModalTotpVerify.jsx [hunk 1]
```diff
@@ -18,28 +18,32 @@ const ModalTotpVerify = ({ show, onClose, onVerify }) => {
...
+        extended={false}
+        tabIndex={1}
+        title="Authenticator Code"
+      />
+    </div>
   );
 };
 
-ModalTotpVerify.propTypes = {
+const ModalWrapper = ({ show, onClose, onVerify }) => (
```
Comment (amass01) [inline src/components/ModalTotpVerify.jsx:37]:
```suggestion
const ModalTotpVerify = ({ show, onClose, onVerify }) => (
```

File: src/components/ModalTotpVerify.jsx [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { Modal, Message } from "pi-ui";
 import VerifyTotp from "src/containers/User/Totp/Verify";
 import { TOTP_CODE_LENGTH } from "src/constants";
 
-const ModalTotpVerify = ({ show, onClose, onVerify }) => {
+const Verify = ({ onClose, onVerify }) => {
```
Comment (amass01) [inline src/components/ModalTotpVerify.jsx:7]:
```suggestion
const ModalTotpVerifyContent = ({ onClose, onVerify }) => {
```
or

```suggestion
const ModalTotpVerifyBody = ({ onClose, onVerify }) => {
```

File: src/components/ModalTotpVerify.jsx [hunk 3]
```diff
@@ -18,28 +18,32 @@ const ModalTotpVerify = ({ show, onClose, onVerify }) => {
...
+);
+
+ModalWrapper.propTypes = {
   show: PropTypes.bool.isRequired,
   onClose: PropTypes.func.isRequired,
   onVerify: PropTypes.func.isRequired
 };
 
-export default ModalTotpVerify;
+export default ModalWrapper;
```
Comment (amass01) [inline src/components/ModalTotpVerify.jsx:49]:
```suggestion
export default ModalTotpVerify;
```

**Review by amass01 — APPROVED** [review]
LGTM, left minor naming improvements.

File: src/components/ModalTotpVerify.jsx (hunk 1 above)
Comment (victorgcramos) [reply src/components/ModalTotpVerify.jsx:37]: 👍

File: src/components/ModalTotpVerify.jsx (hunk 2 above)
Comment (victorgcramos) [reply src/components/ModalTotpVerify.jsx:7]: First one is better. 👍

File: src/components/ModalTotpVerify.jsx (hunk 3 above)
Comment (victorgcramos) [reply src/components/ModalTotpVerify.jsx:49]: 👍

**Review by amass01 — APPROVED** [review]
ACK
