### PR TITLE
[redesign] Fixes proposal form button positions

### LINKED ISSUE #1484: [redesign] Weird action buttons positioning on Edit Proposal mobile view
The action buttons are misaligned. The image above can illustrate the wrong positioning of the elements: 
Screen Shot 2019-10-09 at 21 39 44

### PR DESCRIPTION
**Pull request by thi4go**
closes #1484 and #1487

### CODE REVIEW

File: src/pages/Proposals/Edit.jsx [hunk 1]
```diff
@@ -1,14 +1,39 @@
...
+  const CancelButton = () => (
+    <Button 
+      type="button"
+      kind="secondary"
+      size={mobile ? "sm" : "md"}
+      onClick={() => 
+        history.push(`/proposal/${match.params.token}`)
+      }
+    >
+      {mobile ? <div style={textStyle}>X</div> : "Cancel"}
```
Comment (fernandoabolafio) [inline src/pages/Proposals/Edit.jsx]: hey @thi4go after testing it on my end, this "X" felt a bit meaningless. Can we keep the "cancel" text also for mobile?

Comment (thi4go) [reply src/pages/Proposals/Edit.jsx]: We can, I'll decrease the font-size to make it fit better
