### PR TITLE
fix: proposals lazy list fetching fixes

### LINKED ISSUE #2169: Bug: Proposals list chunks fetching is broken
While working on tlog I experienced a bug in all proposal lists, currently having 5 proposals _is discussion_ but seeing only the first page/chunk which is 4 proposals.

This bug originating in #2084.

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff fixes #2169 , which describes a bug on lazy list for proposals. The proposals were not being fetched after the first initial batch due to a race condition caused by the way we fetch remaining proposals.

### CODE REVIEW

File: src/components/RecordsView/RecordsView.jsx [hunk 1]
```diff
@@ -63,63 +46,45 @@ const RecordsView = ({
...
   const [index, onSetIndex] = useQueryStringWithIndexValue("tab", 0, tabLabels);
   const tabOption = tabLabels[index];
-
-  const filteredTokens = recordTokensByTab[tabOption] || [];
-
   const isMobileScreen = useMediaQuery("(max-width:560px)");
 
-  const filteredRecords =
-    (records && getRecordsByTabOption(records, filteredTokens)) || [];
+  const [filteredRecords, filteredTokens] = getFilteredRecordsAndToken(
```
Comment (amassarwi) [inline src/components/RecordsView/RecordsView.jsx:56]: useMemo maybe ?

**Review by amassarwi — APPROVED** [review]
tACK - nice work @victorgcramos, ended up with cleaner & readable logic.

Left one suggestion.
